version: '3.8'

services:
  app:
    build: 
      context: .
    container_name: app
    ports:
      - "8502:8502"   # FastAPI
      - "8501:8501"   # Streamlit
    expose:
      - "8502"
      - "8501"


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
